# This is a basic workflow that is manually triggered

name: Tests on master push

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install deps
        run: npm install
      - name: Run tests
        run: npm test
